apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: egress-within-namespace
specs:
  - endpointSelector:
      matchLabels: {}
    egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": {{ NAMESPACE }}
