apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-within-namespace
specs:
  - endpointSelector:
      matchLabels: {}
    ingress:
    - fromEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": {{ NAMESPACE }}
